AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Link-Service
  Sample SAM Template for Link-Service

Globals:
  Function:
    Timeout: 3

Resources:
  LinkApi:
    Type: "AWS::Serverless::Api"
    Properties:
      StageName: Prod
      Cors: "'*'"

  LinkServiceFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: link_api/
      Handler: link_service.entrypoints.aws.lambda_handler
      Runtime: python3.9
      Events:

        LinkList:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            RestApiId: !Ref LinkApi
            Path: /links
            Method: get
        LinkDetail:
          Type: Api
          Properties:
            RestApiId: !Ref LinkApi
            Path: /links/{id}
            Method: get
        LinkCreate:
          Type: Api
          Properties:
            RestApiId: !Ref LinkApi
            Path: /links
            Method: post
        LinkUpdate:
          Type: Api
          Properties:
            RestApiId: !Ref LinkApi
            Path: /links/{id}
            Method: put
        LinkDelete:
          Type: Api
          Properties:
            RestApiId: !Ref LinkApi
            Path: /links/{id}
            Method: delete

Outputs:

  LinkServiceFunction:
    Description: "Link Service Lambda Function ARN"
    Value: !GetAtt LinkServiceFunction.Arn
  LinkServiceFunctionIamRole:
    Description: "Implicit IAM Role created for Link Service function"
    Value: !GetAtt LinkServiceFunctionRole.Arn
